### ISSUE TITLE
Service Keys

### ISSUE THREAD

**Issue by jschabowsky** [SolaceSamples/solace-samples-cloudfoundry-java#32]
I think we should explain better that Service Keys are used to get access to the credentials to a VMR being managed by PCF. It is NOT a requirement that they then use the Service Key JSON in runtime... They could.... or they could take the values in the service key and put in a custom config file or other means... The issue is it looks like using this is a requirement when it is just a helper... Some people using Paho do not want to be tied to Solace or PCF so using the Solace PCF Service Key is the opposite of what they would want. 

Also Using the word "somehow" seems somehow ambiguous and confusing.... I would suggest either changing this to provide an example or saying that the service key can be passed into the client by using a file, classpath or VM property (or something like that)

**Comment by Mrc0113** [comment]
Closing stale issue due to inactivity. 😴
To have this issue re-opened please add a comment below with a detailed explanation.
Thank you for your contributions ❤️
