### ISSUE TITLE
The link to Best Practices is broken

### ISSUE THREAD

**Issue by MichaelDavisSolace** [SolaceSamples/solace-samples-cloudfoundry-java#35]
In docs/_includes/into.html, the link labelled "Best Practices for developing applications that use Solace Messaging" is broken. It should be:

https://docs.solace.com/Solace-Messaging-APIs/Developer-Guide/Best-Practices.htm

**Comment by Mrc0113** [comment]
Broken link has since been resolved. Thanks for opening!
