### ISSUE TITLE
Typo and Broken Link

### ISSUE THREAD

**Issue by ghost** [SolaceSamples/solace-samples-cloudfoundry-java#38]
**URL:** [https://solacesamples.github.io/solace-samples-cloudfoundry-java/](https://solacesamples.github.io/solace-samples-cloudfoundry-java/)

1. **Typo:** Under heading **Getting Started Samples**, in the 5th paragraph,  _Please read the Solace MQTT **Tuturial**_.
2. **Broken Link**: Within the ordered list, _5. Best Practices for developing applications that use Solace Messaging_, it's a broken link, it should point to [https://docs.solace.com/Solace-Messaging-APIs/Developer-Guide/Best-Practices.htm](https://docs.solace.com/Solace-Messaging-APIs/Developer-Guide/Best-Practices.htm).

**Comment by Mrc0113** [comment]
Type and Broken link have since been resolved. thanks for opening this!
